source("prepareData.R")
png(filename="plot4.png",width=480, height=480, bg="transparent")
par(mfrow=c(2,2))
plot(x=df$datetime,y=df$Global_active_power,type="l", ylab="Global Active Power", xlab="")
plot(x=df$datetime,y=df$Voltage,type="l", ylab="Voltage", xlab="datetime")
plot(x=df$datetime,y=df$Sub_metering_1,type="l", ylab="Energy sub metering", xlab="")
lines(x=df$datetime,y=df$Sub_metering_2,col="Red",type="l")
lines(x=df$datetime,y=df$Sub_metering_3,col="Blue",type="l")
legend("topright", lty=rep(1,3), col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty='n')
plot(x=df$datetime,y=df$Global_reactive_power,type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()